Format code, remove whitespaces, refactor
AppiumTestDistribution/appium-installer pull request #11
Opened 2023-08-31 11:23 UTC by krishanuc1001

2023-08-31 11:35 UTC, saikrishna321 commented
Is this run against the local prettier config ?

2023-08-31 11:48 UTC, krishanuc1001 commented
> 

No, ran basic formatting on IDE, reverted and pushed another commit after running "npm run prettier" this time. Updated the PR.

2023-08-31 12:34 UTC, saikrishna321 requested changes

2023-08-31 12:34 UTC, saikrishna321 commented on src/serverInstall.js
> -        return;
this is required to return after plugin is updated.

2023-09-01 08:08 UTC, SrinivasanTarget approved these changes

2023-09-01 08:08 UTC, merged